<?php

namespace AppBundle\Repository;

/**
 * TileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TileRepository extends \Doctrine\ORM\EntityRepository
{
}
